"""Aggregated Canopy Model (Williams et al. 1997) -- daily GPP.

**Phase 3. Not yet implemented.** Blocked on the specification.

Inputs: day of year, atmospheric CO2 (umol mol-1), daytime and nighttime air
temperature (degrees C, standing in for daily max/min), daily total shortwave
radiation (MJ m-2 d-1), site latitude, and the parameters for foliar carbon
(g C m-2), leaf mass per area (g C m-2) and canopy efficiency.

Output: gross primary productivity, g C m-2 d-1.

What is still needed
--------------------
* The ten fixed empirical coefficients, with the table or equation number each
  comes from.
* The equations themselves (Eq. 2, 4, 5, 6, 7, 8, 9) and the stated solve order
  2-5-6-4-8-7-9.
* The ``D_T`` half-range definition.
* The frost cutoff threshold and its masking rule.
* The numerical guards.
* Config entries for canopy height ``H`` and leaf water potential ``psi_d``.

Nothing here is to be guessed. Fabricated coefficients produce a model that
runs, samples and converges while being quantitatively meaningless, and nothing
downstream would catch it.

Known problems to verify once the specification lands
-----------------------------------------------------
Measured independently and reported by the project author. Recorded here so
they survive into the thesis limitations rather than being rediscovered late.

**1. ACM is nearly temperature-insensitive at low irradiance.** Measured GPP
across a 40-degree swing at low ``I``:

    T (degC)     +20     +7      0      -10     -20
    GPP          2.646   2.657   2.656  2.648   2.633

A 0.5% response. The cause is structural: at low ``I`` the Eq. 7 light
limitation dominates and GPP collapses to ``E_0 * I * (d1*D_ms + d2)``, in
which ``T`` does not appear at all. The frost cutoff is therefore masking a
**structural insensitivity, not a mild extrapolation error** below the
calibration floor. Keep the cutoff, but do not let this framing get lost: it is
a limitation of the photosynthesis model, not a data-screening detail.

For scale, that floor is not small. Sustained year-round, 2.657 g C m-2 d-1
integrates to about 970 g C m-2 yr-1 -- roughly Hyytiala's entire true annual
GPP, generated by a term with no temperature dependence.

**2. Annual GPP is roughly five times too high.** Over a synthetic
Hyytiala-like year (LAI 3, T from -9 to +19 degC, I from 1 to 27 MJ m-2 d-1,
``ceff`` 40) the measured total was 5009 g C m-2 yr-1 against an observed
Hyytiala value near 1000-1100.

``dalec.diagnostics.gpp_magnitude_gate`` exists to decide this quantitatively
once ACM is wired in, and to block calibration if it cannot be resolved.

**3. The ``ceff`` reading is suspect.** The original ``a1 * N`` form reproduces
Williams et al. Fig. 2 at Harvard Forest (modelled 9.90 against a measured peak
near 11-12), so the implementation is sound. The DALEC2 ``ceff`` substitution
does not behave:

    ceff     10      20      40      60      80      100
    GPP      11.62   14.58   16.55   17.26   17.62   17.83

The bottom of the prior range already exceeds plausible boreal midsummer GPP of
8-11, and a tenfold change in ``ceff`` moves GPP by only 53%, nearly all of it
below ``ceff = 20``. Consistently, ``a1 * N`` at Harvard Forest is
2.95 * 1.92 = 5.7, against a ``ceff`` prior of 10-100 -- ranges that barely
overlap, which is the likely root of both this and problem 2.

Implement Eq. 2 exactly as specified when it arrives. Do not rescale and do not
guess a correction factor; let the magnitude gate decide.

**Test note.** Do not assert that GPP increases monotonically with ``ceff``:
that passes while the parameter is nearly inert across most of its range.
Assert on the *magnitude* of the response instead -- for example that GPP at
``ceff = 100`` exceeds GPP at ``ceff = 10`` by at least some stated multiple --
so the test can actually fail if the substitution is wrong.
"""

from __future__ import annotations

from typing import Final

# ---------------------------------------------------------------------------
# ACM empirical coefficients -- TO BE SUPPLIED FROM Williams et al. (1997)
# ---------------------------------------------------------------------------
# Placeholders only. Do not fill these in from memory or from a secondary
# source; take them from the paper, with the table/equation number recorded.
ACM_COEFFICIENTS: Final[dict[str, float | None]] = {
    "a1": None,
    "a2": None,
    "a3": None,
    "a4": None,
    "a5": None,
    "a6": None,
    "a7": None,
    "a8": None,
    "a9": None,
    "a10": None,
}

raise NotImplementedError(
    "Phase 3 has not been built yet. The ACM specification -- coefficients, "
    "equations, solve order, D_T definition, frost cutoff and numerical guards "
    "-- has not been received. See the module docstring for the full list."
)
